version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: secure-stay-db-instance
    ports:
      - "4006:3306" # Maps host port 4004 to container port 3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: secure_stay
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql # Mount the MySQL data directory to persist data
volumes:
  mysql_data:
    driver: local
